### ISSUE TITLE
Provision to auto index any new file added to the directory

### ISSUE THREAD

**Issue by kushaldas** [farhaanbukhsh/file-indexer#2]
If a new file gets added to the directory, it should be able to auto index that file.

**Comment by farhaanbukhsh** [comment]
Hey I have tried to bring auto-indexing.

This is the approach I have followed:

Whenever you start the server it basically indexes the files as configured in the `RootDirectory`.
I used `fresh` as tools helps me to restart the server when it detects the change in file.

For now the bottle neck it, fresh is not able to recognise nested subdirectories.

**Comment by farhaanbukhsh** [comment]
This is partially fixed so we will keep it open.
